# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
author: Aaron Snowberger
name: UT | 259111
title: 웹프로그래밍기초
email: aaronkr@g.ut.ac.kr
description: >
  259111 - 웹프로그래밍기초 - 교통대학교 - 2023년 2학기
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

url: https://2023-aaronkr.github.io # the base hostname & protocol for your site
baseurl: /ut-web/ # the subpath of your site, e.g. /blog/

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: 2023-aaronkr
google_analytics:
youtube_channel:
rss: # notes rss

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Course Notes
blog_description: Notes written by students and edited by instructors.

# Pagination
paginate: 10
permalink: /notes/:title/
paginate_path: /notes/page:num/

text:
  pagination:
    newer: "Newer"
    older: "Older"

# Comments
disqus_shortname: # put your disqus shortname

# Optional features
show_social_icons: true
enable_anchorjs: true
enable_latexjs: true
enable_katex: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  announcements:
    defaults:
      layout: post
    output: true
    permalink: /announcements/:path/

announcements_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ["_pages"]
exclude: [vendor]

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-paginate
  - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.10.1"
anchorjs_version: "3.2.2"
latexjs_version: "0.11.1"

theme: jekyll-theme-slate
